#!/usr/bin/env python3
"""Regenerates INDEX.md — one line per note, for an agent to read first.

The vault is ~99 notes and ~72,000 words. Reading it whole costs more context
than re-deriving the same facts from the repos, which is exactly why an agent
skips it and the notes go stale. One line per note is about 3,000 words: cheap
enough to load every session, detailed enough to know which two notes to open.

Run after adding or renaming a note:  python3 _workspace/reindex.py
"""
from __future__ import annotations

import pathlib
import re
import subprocess
import sys

VAULT = pathlib.Path(__file__).resolve().parent.parent
FOLDERS = [
    ("architecture", "How the system is put together"),
    ("decisions", "ADRs — a choice, its alternatives, its consequences"),
    ("features", "What someone can do that they could not before"),
    ("bugs", "Defects worth remembering: cause and fix"),
    ("ops", "Deploy, infra, runbooks, incidents"),
    ("research", "Audits and analyses, dated"),
    ("api", "Endpoint notes"),
    ("meeting-notes", "What was agreed, and when"),
]
SKIP_DIRS = {"_templates", "_workspace", ".git", ".obsidian"}

# Lines that are metadata rather than the note's point.
META = re.compile(r"^\s*(?:[-*]\s|\*\*|#|<!--|\||>)")


def summarise(path: pathlib.Path) -> tuple[str, str]:
    """The note's title and its first sentence of actual prose."""
    title, summary, lines = path.stem.replace("-", " "), "", []
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except OSError:
        return title, ""

    body: list[str] = []
    for line in lines:
        if line.startswith("# ") and not summary:
            title = line[2:].strip()
            body = []
            continue
        if META.match(line) or not line.strip():
            continue
        # Metadata blocks wrap, and a wrapped line has no bullet to match on.
        # Two tells: it is still bold-heavy, or it starts mid-sentence.
        if "**" in line:
            continue
        if not body and not line.lstrip()[:1].isupper():
            continue
        body.append(line.strip())
        if len(" ".join(body)) > 40:
            break

    text = " ".join(body)
    # First sentence, or the first 130 characters at a word boundary.
    m = re.match(r"(.+?[.!?])(\s|$)", text)
    summary = m.group(1) if m else text
    if len(summary) > 150:
        summary = summary[:147].rsplit(" ", 1)[0] + "…"
    return title, summary


def last_touched(path: pathlib.Path) -> str:
    """The note's last commit date, or empty when git has never seen it."""
    try:
        out = subprocess.run(
            ["git", "log", "-1", "--format=%ad", "--date=short", "--", str(path)],
            cwd=VAULT, capture_output=True, text=True, timeout=10)
        return out.stdout.strip()
    except (OSError, subprocess.SubprocessError):
        return ""


def main() -> int:
    out = [
        "# Vault index",
        "",
        "*Generated by `_workspace/reindex.py` — do not edit by hand.*",
        "",
        "One line per note, so the whole vault can be surveyed cheaply and only",
        "the relevant notes opened. The notes themselves are the source of truth;",
        "this is a table of contents with hints.",
        "",
    ]
    total = 0
    for folder, blurb in FOLDERS:
        d = VAULT / folder
        if not d.is_dir():
            continue
        notes = sorted(p for p in d.glob("*.md") if p.name != "INDEX.md")
        if not notes:
            continue
        out += [f"## {folder}/", "", f"*{blurb}*", ""]
        for p in notes:
            title, summary = summarise(p)
            date = last_touched(p)
            stamp = f" `{date}`" if date else " `uncommitted`"
            line = f"- [[{p.stem}|{title}]]{stamp}"
            if summary:
                line += f" — {summary}"
            out.append(line)
            total += 1
        out.append("")

    out += ["---", "", f"{total} notes. Regenerate with `python3 _workspace/reindex.py`.", ""]
    (VAULT / "INDEX.md").write_text("\n".join(out), encoding="utf-8")
    print(f"INDEX.md: {total} notes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
